package:
  name: pycoalescence
  version: "1.2.6"

#source:
#  git_rev: v0.13.1
#  git_url: https://github.com/joerick/pyinstrument.git
source:
  path: ../pycoalescence

build:
  script_env:
    - INTEL_LICENSE_FILE
    - BOOST_ROOT
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - cmake >=3.8
    - boost >=1.63
    - gxx_linux-64 # [linux]
#    - clangxx_osx-64 # [osx]
    - gdal >=2.1.0
    - libboost
    - libgdal
    - libcxx
    - sqlite
  run:
    - python
    - boost
    - gdal
    - libboost
    - libgdal
    - libcxx
    - sqlite
about:
  home: tmp
  license: MIT
  license_file: LICENSE.txt
