package:
  name: pycoalescence
  version: "1.2.6"

#source:
#  git_rev: v0.13.1
#  git_url: https://github.com/joerick/pyinstrument.git
source:
  path: dist/pycoalescence

requirements:
  build:
    - python
    - boost
    - gdal
  run:
    - python
    - boost
    - gdal

about:
  home: tmp
  license: MIT
  license_file: LICENSE.txt
