# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            apt-get update && apt-get install -y gdal-bin libboost-dev cmake libgdal-dev
            pip install numpy scipy
            python setup.py install
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd pycoalescence
            python -m unittest discover


      - store_artifacts:
          path: test-reports
          destination: test-reports
          